######################## default configuration ####################
baseURL = "https://meanify.github.io/"
title = "MEANIFY | All the meaning from your data!"
theme = "startup"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "3"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "mfgaspar" # get your shortname form here : https://disqus.com
# google analytics
googleAnalytics = "UA-158955139-1"
# unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "About Us"
URL = "#"
weight = 1

[[menu.main]]
name = "Services"
URL = "about"
weight = 2

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "FAQ"
URL = "faq"
weight = 5

# footer menu left
[[menu.footer_left]]
name = "About Us"
URL = "#"

[[menu.footer_left]]
name = "Quick Start"
URL = "#"


# footer menu middle

# [[menu.footer_middle]]
# name = "Platform"
# URL = "#"

[[menu.footer_middle]]
name = "Features"
URL = "#"

# footer menu right
[[menu.footer_right]]
name = "Privacy Policy"
URL = "privacy-policy"

# [[menu.footer_right]]
# name = "Terms & Conditions"
# URL = "terms-conditions"

[[menu.footer_right]]
name = "FAQ"
URL = "faq"

#################### default parameters ################################
[params]
logo = "images/logo.svg"
logo_width = "80px"
# Meta data
description = "MEANIFY | All the meaning you can get from your data! (smart analytics intelligent innovation modernization iot cloud kubernetes web mobile)"
author = "Meanify"
image = "images/featured.png"
# contact form action
contact_form_action = "https://formspree.io/xeqkwooe" # contact form works with https://formspree.io

########### footer content ##########
footer_menu_left = "Company"
footer_menu_middle = "Product"
footer_menu_right = "Support"
footer_content = "MEANIFY | All the meaning you can get from your data!"
# copyright
copyright = "Copyright &copy; 2021 [Meanify](https://www.meanify.org) All Rights Reserved"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation buttons
[params.navigation_button]
enable = true
label = "Get Started"
link = "contact"

  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/miguel.ferreira.gaspar"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/migfgaspar"

[[params.social]]
title = "skype"
icon = "ti-skype" # themify icon : https://themify.me/themify-icons
link = "https://wa.me/00351962390920"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/company/meanify"

[[params.social]]
title = "git"
icon = "ti-github" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://github.com/meanify"

#[[params.social]]
#title = "instagram"
#icon = "ti-instagram" #ionicon pack v2 : https://ionicons.com/v2/
#link = "https://www.instagram.com/mfgaspar/"