################################# Default configuration ###################
baseURL = "https://meanify.github.io"
title = "MEANIFY | All the meaning from your data!"
theme = "airspace-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "mfgaspar" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  
############################## navigation ###############################

# main menu
[[menu.main]]
name = "About"
URL = "about"
weight = 1

#[[menu.main]]
#name = "Project"
#URL = "project"
#weight = 2

[[menu.main]]
name = "Service"
URL = "service"
weight = 3

#[[menu.main]]
#name = "Blog"
#URL = "blog"
#weight = 4

#[[menu.main]]
#weight = 5
#name = "Pages"
#hasChildren = true

  #[[menu.main]]
  #parent = "Pages"
  #name = "FAQ"
  #URL = "faq"

  #[[menu.main]]
  #parent = "Pages"
  #name = "Pricing"
  #URL = "pricing"
  
[[menu.main]]
name = "Contact"
URL = "contact"
weight = 6


# footer menu
#[[menu.footer]]
#name = "About"
#URL = "about"
#weight = 1

#[[menu.footer]]
#name = "Project"
#URL = "project"
#weight = 2

#[[menu.footer]]
#name = "Service"
#URL = "service"
#weight = 2

#[[menu.footer]]
#name = "FAQ"
#URL = "faq"
#weight = 4

#[[menu.footer]]
#name = "Contact"
#URL = "contact"
#weight = 5


#################### default parameters ################################
[params]
logo = "images/logo.svg"
# Meta data
description = "MEANIFY | All the meaning you can get from your data!"
author = "Meanify"
# Contact Information
location = "ÉvoraTech, Évora, Portugal"
phone = "+351 962 390 920"
phonelink = "00351962390920"
email = "meanify@gmail.com"
emaillink = "meanify@gmail.com"
skype = "Reach out over skype"
skypelink = "miguel.ferreira.gaspar"
# contact form action
contact_form_action = "https://formspree.io/xeqkwooe" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-158955139-1"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = true

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "38.5834705"
map_longitude = "-7.9266024"
map_marker = "images/marker.png"

  
############################# social site ########################
[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/company/meanify"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://twitter.com/migfgaspar"

[[params.social]]
icon = "ion-social-whatsapp-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://wa.me/00351962390920"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/miguel.ferreira.gaspar"

[[params.social]]
icon = "ion-social-instagram-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/mfgaspar/"

#[[params.social]]
#icon = "ion-social-github-outline" #ionicon pack v2 : https://ionicons.com/v2/
#link = "https://github.com/meanify"




################################ English Language ########################
[Languages.en]
languageName = "EN"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# copyright
copyright = "Copyright &copy; 2020 [Meanify](https://meanify.github.io) All Rights Reserved"

################################ Portuguese Language ########################
#[Languages.pt]
#languageName = "PT"
#languageCode = "pt-pt"
#contentDir = "content/portuguese"
#weight = 2
#home = "Inicio"
# copyright
#copyright = "Copyright &copy; 2020 [Meanify](https://meanify.github.io) All Rights Reserved"